[package]
name = "hello-blockchain"
version = "1.0.0"
authors = []

[addresses]
hello_blockchain = '0x29c407f249aae74494cf3071d524aacdcb070684cdc19f3ca0886d88aa5b1aca'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
